openapi: 3.0.0
info:
  title: BL-GPT Binance Price API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /price/{symbol}:
    get:
      summary: Coin fiyatını getir
      parameters:
        - in: path
          name: symbol
          required: true
          schema:
            type: string
          description: Coin sembolü (örnek: BTCUSDT)
      responses:
        '200':
          description: Fiyat bilgisi
          content:
            application/json:
              schema:
                type: object
                properties:
                  coin:
                    type: string
                  price:
                    type: string
